version: '3'
services:
  db:
    image: rethinkdb:latest
    volumes:
      - ./:/data
    ports:  
      - "8080:8080"
  web:
    image: node:alpine    
    volumes:
      - ./startup:/usr/startup
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: /usr/startup/startup.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
